- name: Install tasks
  hosts: local
  connection: local
  become: true

  tasks:
  - name: Install htop
    package:
      name: htop
      state: present
  - name: Install python3-pip
    package:
      name: python3-pip
      state: present

- name: Install Nginx locally
  become: true
  hosts: all
  connection: local
  roles:
   - nginxinc.nginx
