---
- name: instaluj taski
  hosts: local
  connection: local
  become: true

  tasks:
  - name: Zainstaluj htop
    package:
      name: htop
      state: present
  - name: zainstaluj python3-pip
    package:
      name: python3-pip
      state: present

- name: Install Nginx locally
  become: true
  hosts: all
  connection: local
  roles:
   - nginxinc.nginx
